apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-gateway
  namespace: system-plane
spec:
  podSelector:
    matchLabels:
      app: db-gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - port: 5432
          protocol: TCP
  egress:
    - to: []
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to: []
      ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              platform.loonaris.tech/tenant: "true"
      ports:
        - port: 5432
          protocol: TCP